### PR TITLE
Remove GPL - replace colorize with rainbow gem

### PR DESCRIPTION
**Pull request by CyborgMaster**
The currently used `colorize` gem is released under the GPL license which is incompatible with this library's MIT license.  Swap that one out for the `rainbow` gem, which is released under the MIT license.

### CODE REVIEW

**Comment by CyborgMaster** [comment]
Any thoughts?

**Comment by CyborgMaster** [comment]
Checking in again.

**Comment by meagar** [comment]
Thanks for this. Sorry it took 4 years to approve.

**Comment by CyborgMaster** [comment]
Cool! Thanks for the merge! Always fun to have these old PRs closed out.

**Pull request merged**
